### ISSUE TITLE
Non unique job_id in config.yaml should throw an error

### ISSUE THREAD

**Issue by enricorotundo** [bacalhau-project/amplify#69]
See this error: https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1681807393198339?thread_ts=1681754897.016109&cid=C02RLM3JHUY

**Comment by philwinder** [comment]
Turns out it's perfectly fine to have duplicate keys in json/yaml. No easy way to fix this without a custom parser. So I'm going to ignore this if that's ok.
